"""Adding collaborators field in database 1

Revision ID: 3a53a5f9f408
Revises: 3b8caf6a6634
Create Date: 2024-10-14 15:47:14.931704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a53a5f9f408'
down_revision: Union[str, None] = '3b8caf6a6634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
