"""Adding collaborators field in database

Revision ID: 3b8caf6a6634
Revises: 3f246a17fb68
Create Date: 2024-10-14 12:38:59.031442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8caf6a6634'
down_revision: Union[str, None] = '3f246a17fb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('collaborators', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'collaborators')
    # ### end Alembic commands ###
