"""Adding collaborators field in database 3

Revision ID: afc25b9c8850
Revises: 3e178abdfbed
Create Date: 2024-10-14 15:49:47.524002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc25b9c8850'
down_revision: Union[str, None] = '3e178abdfbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('collaborators', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'collaborators')
    # ### end Alembic commands ###
